/**
 * Externalized interface strings (NFR-X2): EN + SK at launch, bundle-level
 * replaceable later (02 §Content localization). The catalog pattern: every
 * room migrates its copy here; `t` falls back to English so a missing
 * translation is a gap, never a crash. Copy voice rules (06 §Copy) apply to
 * every locale equally — kind, plain, unhurried, no urgency.
 */

const en = {
  'threshold.quietLine': 'The day is on the other side of this screen.',
  'threshold.morningCompass': 'the morning compass',
  'threshold.eveningCompass': 'the evening compass',
  'threshold.opening': 'today’s opening',
  'threshold.reading': 'one deep thing',
  'threshold.path': 'a path',
  'threshold.quizzes': 'the quizzes',
  'threshold.craving': 'i feel the pull',
  'threshold.realign': 'the weekly realignment',
  'threshold.mirror': 'the mirror',
  'threshold.untangling': 'the untangling',
  'threshold.redesign': 'redesign the phone',
  'threshold.build': 'build one thing',
  'threshold.unplug': 'unplug',
  'threshold.detox': 'dopamine detox',
  'threshold.journal': 'the journal',
  'threshold.settings': 'settings',
  'common.goOn': 'go on',
  'common.yes': 'yes',
  'common.notNow': 'not now',
  'common.skip': 'skip',
  'breath.invitation': 'breathe in… and out',
  'onb.sentence': 'You were not made to be harvested.',
  'onb.question': 'What would you give your attention to, if it were fully yours again?',
  'onb.questionHint': 'one line is enough',
  'onb.terminal': 'That is enough for today. Go live.',
  'morning.question': 'What will you give your attention to today?',
  'morning.questionHint': 'one line, or one word',
  'morning.openingLabel': 'today’s opening',
  'morning.noThread':
    'No thread is being loosened yet. Today is open — give it to what you just named.',
  'morning.iWill': 'i will',
  'morning.terminal': 'Now go give it your attention.',
  'evening.lean': 'Which way did today lean?',
  'evening.linePrompt': 'A line about it, if you wish.',
  'evening.gratitudeQuestion': 'What were you given today?',
  'evening.gratitudeHint': 'Up to three things — or none.',
  'evening.foldKindness': 'Was there a kindness in your day — given or received?',
  'evening.foldCare': 'Did you take care of something that matters?',
  'evening.foldAliveness': 'When did you feel most alive?',
  'evening.foldTheDay': 'fold the day',
  'evening.goodNight': 'good night',
  'evening.windDownFirst': 'wind down first',
  'evening.restTerminal': 'That is enough for today. Rest now.',
  'evening.sleepTerminal': 'The day is folded. Now sleep.',
  'likert.never': 'never',
  'likert.rarely': 'rarely',
  'likert.sometimes': 'sometimes',
  'likert.often': 'often',
  'likert.always': 'always',
  'intake.enoughForNow': 'enough for now',
  'intake.casualtiesDone': 'that is what it touched',
  'intake.doneTerminal': 'The Mirror has what it needs. Go live — it will be ready when you return.',
  'intake.pausedTerminal': 'Nothing is lost. The Mirror waits as long as you need.',
  'portrait.seen': 'i have seen it',
  'portrait.measureAgain': 'measure again',
  'portrait.mapTerminal': 'That is the shape of it — not a verdict, a map. Go live.',
  'portrait.onbTerminal': 'That is enough for today. Go live.',
  'portrait.firstThread': 'One channel per season — loosened slowly, never all at once. Which thread first?',
  'portrait.beginWith': 'begin with',
  'portrait.notYet': 'not yet',
  'help.lead':
    'Before anything else: what you carry sounds heavy, and it deserves a real person, not a screen.',
  'help.footer':
    'Inward is not therapy and holds no answers a doctor or a friend should hold. This page will step aside whenever you are ready.',
  'help.continue': 'i have what i need — go on',
  'vow.cue': 'When does the pull usually find you?',
  'vow.cueHint': 'in bed, after dinner, the moment I wake…',
  'vow.routine': 'And what happens then — the old routine?',
  'vow.routineHint': 'I open the feed and an hour disappears…',
  'vow.gives': 'Be honest: what does it give you?',
  'vow.givesHint': 'a rest from thinking, company, numbness…',
  'vow.vow': 'Now the vow — when the cue comes, what will you do instead?',
  'vow.vowHint': 'When I reach for my phone in bed, I will open the book on my nightstand.',
  'vow.micro': 'And the smallest daily act — under five minutes, doable on your worst day?',
  'vow.microHint': 'one page, one stretch, one message to a friend…',
  'vow.terminal': 'The vow is made. Go live it once, today.',
  'opening.done': 'done — it happened',
  'opening.notToday': 'not today',
  'opening.doneTerminal': 'It counts because it happened. Go on with your day.',
  'opening.leftTerminal': 'The opening waits, without keeping score.',
  'dare.itIsDone': 'it is done',
  'dare.feelHint': 'done — how did it feel?',
  'redesign.lead': 'The phone can be made quieter, once. Do any of these, or none.',
  'redesign.enough': 'that is enough',
  'redesign.terminal': 'The phone is quieter now. It will not ask you about this again.',
  'build.question': 'One thing your hands will build this season. Name it.',
  'build.hint': 'bread, a song, a bench, a garden bed…',
  'build.nameIt': 'name it',
  'build.terminal': 'Named. Once a week the question will come: did your hands learn something?',
  'graduation.line': 'Four weeks held. The thread is loosened — wear the season lightly.',
  'quiet.unplugQuestion': 'How long do you want to be gone?',
  'quiet.oneHour': '1 hour',
  'quiet.hours': 'hours',
  'quiet.designStillness': 'design the stillness window',
  'quiet.veil': 'Unplugged. The world is on.',
  'quiet.stillnessVeil': 'Stillness, kept. The world can hold itself for an hour.',
  'detox.howLong': 'How long a clearing?',
  'detox.seven': 'seven days',
  'detox.fourteen': 'fourteen days',
  'detox.thirty': 'thirty days',
  'detox.redList': 'Which channels go on the red list?',
  'detox.begin': 'begin the clearing',
  'detox.begunTerminal': 'The clearing has begun. Shorter feeds go first — one line a day is all it asks.',
  'detox.oneLine': 'One line about today.',
  'detox.keepIt': 'keep it',
  'detox.closing': 'The clearing is over. How does this feel, compared to before?',
  'detox.finish': 'finish',
  'detox.keptTerminal': 'Kept. The clearing holds — go live the rest of it.',
  'detox.doneTerminal': 'The clearing is done. Keep what it gave you.',
  'stillness.whichDay': 'One window a week, kept for stillness. Which day?',
  'stillness.window': 'From which hour, and for how long?',
  'stillness.startHour': 'starting hour (0–23)',
  'stillness.hoursOf': 'hours of stillness',
  'stillness.keep': 'keep this window',
  'stillness.keptTerminal': 'The window is kept. The app will defend it — you only have to arrive.',
  'common.backToThreshold': 'back to the threshold',
  'journal.search': 'find your own words',
  'journal.soulNotScore': 'written for the soul, not the score',
  'journal.beginning': 'the beginning',
  'journal.empty': 'nothing here yet — the evenings will fill it',
  'crave.hungerQuestion': 'What are you actually hungry for?',
  'crave.connection': 'someone — connection',
  'crave.rest': 'rest',
  'crave.meaning': 'something that matters',
  'crave.body': 'my body wants something',
  'crave.unsure': 'i honestly don’t know',
  'crave.illDoIt': 'i’ll do it',
  'crave.notThisOne': 'not this one',
  'crave.done': 'done',
  'crave.terminal': 'The hunger was real. The feed was not the food. Go.',
  'reading.read': 'i have read it',
  'reading.liveIt': 'Now go live it.',
  'common.iSeeIt': 'i see it',
  'widget.keepIt': 'keep it',
  'widget.prompt': 'What is alive right now?',
  'widget.terminal': 'Kept. Now stay with it.',
  'quiz.statedQuestion': 'What do you say matters most? Pick a few.',
  'quiz.statedDone': 'that is what i say',
  'quiz.livedQuestion': 'And which of them received an unhurried hour this week?',
  'quiz.livedDone': 'honestly, that',
  'path.dayAct': 'the day’s act',
  'path.dayDone': 'done — it happened',
  'path.carryIt': 'i will carry it into the day',
  'path.finish': 'finish the path',
  'path.keptTerminal': 'The day is walked. The next opens tomorrow.',
  'path.walkedTerminal': 'The path is walked. Keep walking without it.',
  'perm.yes': 'yes',
  'perm.notNow': 'not now',
  'realign.ledgerQuestion': 'The ledger: what did you treat as ultimate, in practice?',
  'realign.screens': 'hours to screens, your honest guess',
  'realign.wanting': 'money to wanting, not needing',
  'realign.lovedQuestion': 'And the hours that reached what you say you love?',
  'realign.loved': 'hours to what you love',
  'realign.commit': 'commit',
  'realign.commitQuestion': 'One commitment for the week ahead — yours, in your words.',
  'realign.terminal': 'The week is read. Now go write the next one.',
  'settings.howScore': 'how the score works',
  'settings.howScoreClose': 'how the score works — close',
  'settings.erase': 'erase everything',
  'settings.eraseNow': 'erase it all now',
  'settings.keepThings': 'keep my things',
  'disclosure.whatTitle': 'what the index is',
  'disclosure.whatBody':
    'Each channel gets a capture score from 0 to 100, built from three parts: time ({time}), pull ({pull}), and what it displaces ({displacement}). Nothing else feeds it. No score ever changes what the app offers you.',
  'disclosure.timeTitle': 'time',
  'disclosure.timeBody':
    'Your weekly hours, from your own answer — or from measured screen time if you allowed it (the measurement wins over the guess). Each channel has its own thresholds; more hours, higher score.',
  'disclosure.pullTitle': 'pull',
  'disclosure.pullBody': 'Five plain questions per channel, each answered never to always:\n{items}',
  'disclosure.displacementTitle': 'what it displaces',
  'disclosure.displacementBody':
    'Named casualties add fixed weights: sleep {sleep}, a close relationship {relationship}, money {finances}, a skill {skill}, your body {body}, meals with people {meals}.',
  'disclosure.evidenceTitle': 'how living lowers it',
  'disclosure.evidenceBody':
    'Counted journal entries push a channel’s score down — kindness {kindness}, care {care}, aliveness {aliveness}, a finished dare {dare}, a decoded craving {craving}, gratitude {gratitude} — over the trailing {window} days, capped at {cap} points per channel. Entries about other channels count at {cross}.',
  'disclosure.countingTitle': 'what counts',
  'disclosure.countingBody':
    'An entry counts when it is concrete — a named person, place, or thing, something that happened, at least {minWords} words. At most {dailyCap} entries count per day, one per kind for the ones you write by hand. Repeating yourself within {similarDays} days halves the weight each time (×{decay}). Entries that do not count are still kept — written for the soul, not the score.',
  'disclosure.bandsTitle': 'smoothing and bands',
  'disclosure.bandsBody':
    'Scores are averaged over the last {weeks} weeks, so one loud week is not a verdict. Bands: free up to {free}, leaking up to {leaking}, caught above that. The headline level weighs the deepest captures most.',
  'disclosure.neverTitle': 'what never happens',
  'disclosure.neverBody':
    'The index never leaves this device. It is never used to time, tempt, or sell anything. Erasing your data erases it entirely.',
} as const;

export type StringKey = keyof typeof en;

const sk: Partial<Record<StringKey, string>> = {
  'threshold.quietLine': 'Deň je na druhej strane tejto obrazovky.',
  'threshold.morningCompass': 'ranný kompas',
  'threshold.eveningCompass': 'večerný kompas',
  'threshold.opening': 'dnešné otvorenie',
  'threshold.reading': 'jedna hlboká vec',
  'threshold.path': 'cesta',
  'threshold.quizzes': 'kvízy',
  'threshold.craving': 'cítim to nutkanie',
  'threshold.realign': 'týždenné zrovnanie',
  'threshold.mirror': 'zrkadlo',
  'threshold.untangling': 'rozplietanie',
  'threshold.redesign': 'upokojiť telefón',
  'threshold.build': 'vytvor jednu vec',
  'threshold.unplug': 'odpojiť sa',
  'threshold.detox': 'dopamínový pôst',
  'threshold.journal': 'denník',
  'threshold.settings': 'nastavenia',
  'common.goOn': 'ďalej',
  'common.yes': 'áno',
  'common.notNow': 'teraz nie',
  'common.skip': 'preskočiť',
  'breath.invitation': 'nádych… a výdych',
  'onb.sentence': 'Nebol si stvorený na to, aby ťa žali.',
  'onb.question': 'Čomu by si venoval svoju pozornosť, keby bola znova celá tvoja?',
  'onb.questionHint': 'stačí jeden riadok',
  'onb.terminal': 'Na dnes to stačí. Choď žiť.',
  'morning.question': 'Čomu dnes venuješ svoju pozornosť?',
  'morning.questionHint': 'jeden riadok, alebo jedno slovo',
  'morning.openingLabel': 'dnešné otvorenie',
  'morning.noThread':
    'Žiadna niť sa zatiaľ nerozplieta. Dnešok je otvorený — daj ho tomu, čo si práve pomenoval.',
  'morning.iWill': 'dám',
  'morning.terminal': 'Teraz tomu choď venovať svoju pozornosť.',
  'evening.lean': 'Na ktorú stranu sa dnešok naklonil?',
  'evening.linePrompt': 'Ak chceš, jeden riadok o tom.',
  'evening.gratitudeQuestion': 'Čo ti dnes bolo dané?',
  'evening.gratitudeHint': 'Najviac tri veci — alebo žiadna.',
  'evening.foldKindness': 'Bola v tvojom dni láskavosť — daná či prijatá?',
  'evening.foldCare': 'Postaral si sa o niečo, na čom záleží?',
  'evening.foldAliveness': 'Kedy si sa cítil najviac živý?',
  'evening.foldTheDay': 'zložiť deň',
  'evening.goodNight': 'dobrú noc',
  'evening.windDownFirst': 'najprv stíšenie',
  'evening.restTerminal': 'Na dnes to stačí. Teraz odpočívaj.',
  'evening.sleepTerminal': 'Deň je zložený. Teraz spi.',
  'likert.never': 'nikdy',
  'likert.rarely': 'zriedka',
  'likert.sometimes': 'niekedy',
  'likert.often': 'často',
  'likert.always': 'vždy',
  'intake.enoughForNow': 'nateraz stačí',
  'intake.casualtiesDone': 'toho sa to dotklo',
  'intake.doneTerminal': 'Zrkadlo má, čo potrebuje. Choď žiť — bude pripravené, keď sa vrátiš.',
  'intake.pausedTerminal': 'Nič nie je stratené. Zrkadlo počká, ako dlho potrebuješ.',
  'portrait.seen': 'videl som to',
  'portrait.measureAgain': 'zmerať znova',
  'portrait.mapTerminal': 'Taký je jeho tvar — nie rozsudok, mapa. Choď žiť.',
  'portrait.onbTerminal': 'Na dnes to stačí. Choď žiť.',
  'portrait.firstThread': 'Jeden kanál za sezónu — rozpletaný pomaly, nikdy všetko naraz. Ktorá niť ako prvá?',
  'portrait.beginWith': 'začni s',
  'portrait.notYet': 'ešte nie',
  'help.lead':
    'Skôr než čokoľvek iné: to, čo nesieš, znie ťažko — a zaslúži si skutočného človeka, nie obrazovku.',
  'help.footer':
    'Inward nie je terapia a nedrží odpovede, ktoré patria lekárovi alebo priateľovi. Táto stránka ustúpi, kedykoľvek budeš pripravený.',
  'help.continue': 'mám, čo potrebujem — ďalej',
  'vow.cue': 'Kedy ťa to nutkanie zvyčajne nachádza?',
  'vow.cueHint': 'v posteli, po večeri, hneď po prebudení…',
  'vow.routine': 'A čo sa stane potom — tá stará rutina?',
  'vow.routineHint': 'otvorím feed a hodina zmizne…',
  'vow.gives': 'Buď úprimný: čo ti to dáva?',
  'vow.givesHint': 'oddych od myslenia, spoločnosť, otupenie…',
  'vow.vow': 'A teraz sľub — keď príde ten podnet, čo urobíš namiesto toho?',
  'vow.vowHint': 'Keď v posteli siahnem po telefóne, otvorím knihu na nočnom stolíku.',
  'vow.micro': 'A najmenší denný čin — do päť minút, zvládnuteľný aj v najhorší deň?',
  'vow.microHint': 'jedna strana, jeden strečing, jedna správa priateľovi…',
  'vow.terminal': 'Sľub je daný. Choď ho dnes raz žiť.',
  'opening.done': 'hotovo — stalo sa',
  'opening.notToday': 'dnes nie',
  'opening.doneTerminal': 'Počíta sa, lebo sa to stalo. Pokračuj vo svojom dni.',
  'opening.leftTerminal': 'Otvorenie počká, bez počítania.',
  'dare.itIsDone': 'je to za mnou',
  'dare.feelHint': 'hotovo — aké to bolo?',
  'redesign.lead': 'Telefón sa dá raz upokojiť. Urob čokoľvek z tohto, alebo nič.',
  'redesign.enough': 'to stačí',
  'redesign.terminal': 'Telefón je teraz tichší. Už sa ťa na to nebude pýtať.',
  'build.question': 'Jedna vec, ktorú tvoje ruky túto sezónu vytvoria. Pomenuj ju.',
  'build.hint': 'chlieb, pieseň, lavička, hriadka…',
  'build.nameIt': 'pomenovať',
  'build.terminal': 'Pomenované. Raz za týždeň príde otázka: naučili sa tvoje ruky niečo?',
  'graduation.line': 'Štyri týždne vydržané. Niť je rozpletená — nos túto sezónu zľahka.',
  'quiet.unplugQuestion': 'Na ako dlho chceš byť preč?',
  'quiet.oneHour': '1 hodina',
  'quiet.hours': 'hodiny',
  'quiet.designStillness': 'navrhnúť okno ticha',
  'quiet.veil': 'Odpojený. Svet beží ďalej.',
  'quiet.stillnessVeil': 'Ticho, dodržané. Svet sa hodinu udrží aj sám.',
  'detox.howLong': 'Ako dlhé prečistenie?',
  'detox.seven': 'sedem dní',
  'detox.fourteen': 'štrnásť dní',
  'detox.thirty': 'tridsať dní',
  'detox.redList': 'Ktoré kanály idú na červený zoznam?',
  'detox.begin': 'začať prečistenie',
  'detox.begunTerminal': 'Prečistenie sa začalo. Kratšie feedy idú prvé — stačí jeden riadok denne.',
  'detox.oneLine': 'Jeden riadok o dnešku.',
  'detox.keepIt': 'uložiť',
  'detox.closing': 'Prečistenie sa skončilo. Aké to je, v porovnaní s predtým?',
  'detox.finish': 'dokončiť',
  'detox.keptTerminal': 'Uložené. Prečistenie drží — choď žiť jeho zvyšok.',
  'detox.doneTerminal': 'Prečistenie je hotové. Nechaj si, čo ti dalo.',
  'stillness.whichDay': 'Jedno okno týždenne, držané pre ticho. Ktorý deň?',
  'stillness.window': 'Od ktorej hodiny a na ako dlho?',
  'stillness.startHour': 'začiatočná hodina (0–23)',
  'stillness.hoursOf': 'hodiny ticha',
  'stillness.keep': 'ponechať toto okno',
  'stillness.keptTerminal': 'Okno je dohodnuté. Aplikácia ho ochráni — ty máš len prísť.',
  'common.backToThreshold': 'späť na prah',
  'journal.search': 'nájdi vlastné slová',
  'journal.soulNotScore': 'písané pre dušu, nie pre skóre',
  'journal.beginning': 'začiatok',
  'journal.empty': 'zatiaľ tu nič nie je — večery to naplnia',
  'crave.hungerQuestion': 'Po čom si vlastne hladný?',
  'crave.connection': 'niekto — blízkosť',
  'crave.rest': 'odpočinok',
  'crave.meaning': 'niečo, na čom záleží',
  'crave.body': 'moje telo niečo chce',
  'crave.unsure': 'úprimne neviem',
  'crave.illDoIt': 'urobím to',
  'crave.notThisOne': 'toto nie',
  'crave.done': 'hotovo',
  'crave.terminal': 'Hlad bol skutočný. Feed nebol jedlo. Choď.',
  'reading.read': 'prečítal som to',
  'reading.liveIt': 'Teraz to choď žiť.',
  'common.iSeeIt': 'vidím to',
  'widget.keepIt': 'uložiť',
  'widget.prompt': 'Čo je práve teraz živé?',
  'widget.terminal': 'Uložené. Teraz pri tom zostaň.',
  'quiz.statedQuestion': 'Čo hovoríš, že je najdôležitejšie? Vyber pár vecí.',
  'quiz.statedDone': 'toto hovorím',
  'quiz.livedQuestion': 'A ktoré z nich tento týždeň dostali pokojnú hodinu?',
  'quiz.livedDone': 'úprimne, tieto',
  'path.dayAct': 'čin dňa',
  'path.dayDone': 'hotovo — stalo sa',
  'path.carryIt': 'ponesiem si to do dňa',
  'path.finish': 'dokončiť cestu',
  'path.keptTerminal': 'Deň je prejdený. Ďalší sa otvorí zajtra.',
  'path.walkedTerminal': 'Cesta je prejdená. Kráčaj ďalej aj bez nej.',
  'perm.yes': 'áno',
  'perm.notNow': 'teraz nie',
  'realign.ledgerQuestion': 'Účet: čomu si v praxi pripisoval najvyššiu hodnotu?',
  'realign.screens': 'hodiny obrazovkám, tvoj úprimný odhad',
  'realign.wanting': 'peniaze chceniu, nie potrebe',
  'realign.lovedQuestion': 'A hodiny, ktoré sa dostali k tomu, čo miluješ?',
  'realign.loved': 'hodiny tomu, čo miluješ',
  'realign.commit': 'zaviazať sa',
  'realign.commitQuestion': 'Jeden záväzok na budúci týždeň — tvoj, tvojimi slovami.',
  'realign.terminal': 'Týždeň je prečítaný. Teraz choď napísať ďalší.',
  'settings.howScore': 'ako funguje skóre',
  'settings.howScoreClose': 'ako funguje skóre — zavrieť',
  'settings.erase': 'vymazať všetko',
  'settings.eraseNow': 'vymazať všetko teraz',
  'settings.keepThings': 'nechať si svoje veci',
  'disclosure.whatTitle': 'čo je index',
  'disclosure.whatBody':
    'Každý kanál dostáva skóre zachytenia od 0 do 100, zložené z troch častí: čas ({time}), ťah ({pull}) a čo vytláča ({displacement}). Nič iné doň nevstupuje. Žiadne skóre nikdy nemení, čo ti aplikácia ponúka.',
  'disclosure.timeTitle': 'čas',
  'disclosure.timeBody':
    'Tvoje týždenné hodiny, z tvojej vlastnej odpovede — alebo z nameraného času pri obrazovke, ak si to dovolil (meranie vyhráva nad odhadom). Každý kanál má vlastné prahy; viac hodín, vyššie skóre.',
  'disclosure.pullTitle': 'ťah',
  'disclosure.pullBody': 'Päť jednoduchých otázok na kanál, každá od nikdy po vždy:\n{items}',
  'disclosure.displacementTitle': 'čo vytláča',
  'disclosure.displacementBody':
    'Pomenované straty pridávajú pevné váhy: spánok {sleep}, blízky vzťah {relationship}, peniaze {finances}, zručnosť {skill}, tvoje telo {body}, jedlá s ľuďmi {meals}.',
  'disclosure.evidenceTitle': 'ako ho žitie znižuje',
  'disclosure.evidenceBody':
    'Započítané zápisy v denníku tlačia skóre kanála nadol — láskavosť {kindness}, starostlivosť {care}, živosť {aliveness}, dokončená výzva {dare}, rozlúštené nutkanie {craving}, vďačnosť {gratitude} — za posledných {window} dní, najviac {cap} bodov na kanál. Zápisy o iných kanáloch sa počítajú na {cross}.',
  'disclosure.countingTitle': 'čo sa počíta',
  'disclosure.countingBody':
    'Zápis sa počíta, keď je konkrétny — pomenovaný človek, miesto alebo vec, niečo, čo sa stalo, aspoň {minWords} slová. Najviac {dailyCap} zápisy denne, jeden od každého ručne písaného druhu. Opakovanie do {similarDays} dní zakaždým zníži váhu na polovicu (×{decay}). Zápisy, ktoré sa nepočítajú, zostávajú — písané pre dušu, nie pre skóre.',
  'disclosure.bandsTitle': 'vyhladzovanie a pásma',
  'disclosure.bandsBody':
    'Skóre sa priemeruje za posledné {weeks} týždne, takže jeden hlučný týždeň nie je rozsudok. Pásma: voľný do {free}, presakuje do {leaking}, chytený nad tým. Hlavná úroveň váži najhlbšie zachytenia najviac.',
  'disclosure.neverTitle': 'čo sa nikdy nestane',
  'disclosure.neverBody':
    'Index nikdy neopustí toto zariadenie. Nikdy sa nepoužíva na časovanie, lákanie ani predávanie. Vymazanie tvojich dát ho vymaže celý.',
};

const CATALOGS: Record<string, Partial<Record<StringKey, string>>> = { en, sk };

/** Locale string, falling back to English — a gap, never a crash (NFR-X2). */
export function t(key: StringKey, locale: string): string {
  const language = locale.toLowerCase().split(/[-_]/)[0];
  return CATALOGS[language]?.[key] ?? en[key];
}

/** Templated string: `{name}` tokens replaced from vars (disclosure pages). */
export function tf(key: StringKey, locale: string, vars: Record<string, string | number>): string {
  return t(key, locale).replace(/\{(\w+)\}/g, (match, name) =>
    name in vars ? String(vars[name]) : match,
  );
}
